= Changelog
:url-repo: https://github.com/spring-io/asciidoctor-extensions

This document provides a summary of all notable changes to this project by release.
For a detailed view of what's changed, refer to the {url-repo}/commits[commit history] of this project.

== 1.0.0-alpha.8 (2022-12-23)

_No changes since previous release._

== 1.0.0-alpha.7 (2022-12-17)

_No changes since previous release._

== 1.0.0-alpha.6 (2022-12-14)

_No changes since previous release._

== 1.0.0-alpha.5 (2022-12-11)

=== Added

* Add Asciidoctor code import extension

=== Fixed

* Register each extension as an extension group
* Update license comment in browser files

== 1.0.0-alpha.4 (2022-12-06)

=== Added

* Add development quickstart to README

=== Changed

* Relocate package from `@opendevise/springio-asciidoctor-extensions` to `@springio/asciidoctor-extensions`

== 1.0.0-alpha.3 (2022-12-02)

=== Fixed

* Use correct source language (`kotlin`) when looking for Kotlin code blocks
* When copying code to clipboard, always clone code block if it contains fold blocks

== 1.0.0-alpha.2 (2022-12-02)

=== Fixed

* Update CSS class prefix for toggling display of fold blocks

== 1.0.0-alpha.1 (2022-12-02)

_Initial prerelease._
